# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_2 || ORIG_REF_NAME==design_1_clk_wiz_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_5/design_1_microblaze_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_5 || ORIG_REF_NAME==design_1_microblaze_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_3/design_1_axi_uartlite_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_3 || ORIG_REF_NAME==design_1_axi_uartlite_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_5/design_1_dlmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_5 || ORIG_REF_NAME==design_1_dlmb_v10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_5/design_1_ilmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_5 || ORIG_REF_NAME==design_1_ilmb_v10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_5/design_1_dlmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_5 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_5/design_1_ilmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_5 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_5/design_1_lmb_bram_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_5 || ORIG_REF_NAME==design_1_lmb_bram_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_3/design_1_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_3/design_1_microblaze_0_axi_intc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_3/design_1_microblaze_0_xlconcat_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_3 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_5/design_1_mdm_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_5 || ORIG_REF_NAME==design_1_mdm_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_5/design_1_mig_7series_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_5 || ORIG_REF_NAME==design_1_mig_7series_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_81M_3/design_1_rst_mig_7series_0_81M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_81M_3 || ORIG_REF_NAME==design_1_rst_mig_7series_0_81M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
